export const NAME = 'Emma Cline'
export const PHONE_NUMBER = '+1-669-666-4508'
export const EMAIL = 'emma@cline.engineer'
export const PERSONAL_WEBSITE = 'emma.cline.engineer'
export const LINKEDIN = 'linkedin.com/in/EmmaJaneAdams'
export const GITLAB = 'gitlab.com/EmmaJCline'
export const TWITTER = 'twitter.com/Emma_J_Adams'
